from graphviz import Digraph
from pathlib import Path

OUTPUT_DIR = Path(__file__).resolve().parent.parent / "output"
# OUTPUT_DIR = Path(__file__).resolve().parent.parent / "output/toyy_sol"  
OUTPUT_DIR.mkdir(exist_ok=True)

# Shared typography settings for figures generated by TERPlots.
PLOT_TITLE_SIZE = 16
PLOT_AXIS_LABEL_SIZE = 13
PLOT_LEGEND_SIZE = 12

def flowChart_heu_basic():

    g = Digraph(format='png')
    g.attr(rankdir='TB')

    # --- Configuration des Styles ---

    # Vert pour le début et la fin (Cercles/Ellipses)
    g.attr('node', style='filled', color='seagreen', fillcolor='honeydew', shape='ellipse')
    g.node('A', 'Début Heuristique basique')
    g.node('J', 'Solution finale')

    # Orange pour les questions (Losanges)
    g.attr('node', color='darkorange', fillcolor='papayawhip', shape='diamond')
    g.node('E', 'Date d\'interruption réalisable?')
    g.node('H', 'Plus de centrales?')

    # Bleu pour les actions (Rectangles)
    g.attr('node', color='steelblue', fillcolor='aliceblue', shape='box')
    g.node('B', 'Calculer scores de priorité Wi')
    g.node('C', 'Trier les centrales par Wi décroissant')
    g.node('D', 'Sélectionner la première centrale') # REDO the french
    g.node('F', 'Planifier l\'interruption\nMettre à jour y, x')
    g.node('G', 'Rien planifier')
    g.node('I', 'Résoudre le PL pour p, s, r')

    # --- Définition des Arêtes ---
    g.edges([('A','B'), ('B','C'), ('C','D'), ('D','E')])
    g.edge('E', 'F', label='Yes')
    g.edge('E', 'G', label='No')
    g.edge('G', 'H')
    g.edge('F', 'H')
    g.edge('H', 'D', label='Yes')
    g.edge('H', 'I', label='No')
    g.edge('I', 'J')

    g.render(str(OUTPUT_DIR / 'heuristic_basic_flowchart'), view=True)

from graphviz import Digraph
def flowChart_heu_improved_extension():

    g = Digraph(format='png')
    g.attr(rankdir='TB')

    # Style général
    g.attr(
        'node',
        style='filled',
        color='steelblue',
        fillcolor='aliceblue',
        shape='box',
        fontsize='14'
    )

    # Noeuds
    g.node('A', 'Résoudre le PL\npour p, s, r')

    g.node(
        'B',
        'Fixer x selon r > 0\n'
        'ET\n'
        'Déduire y à partir de x'
    )

    g.node('C', 'Résoudre à nouveau\nle PL pour p, s, r')

    # Fin
    g.attr(
        'node',
        style='filled',
        color='seagreen',
        fillcolor='honeydew',
        shape='ellipse'
    )

    g.node('D', 'Solution finale')

    # Arêtes
    g.edge('A', 'B')
    g.edge('B', 'C')
    g.edge('C', 'D')

    # Render
    g.render(
        str(OUTPUT_DIR / 'heuristic_improved_extension'),
        view=True
    )

def flowChart_heu_campaign_multiple():

    g = Digraph(format='png')
    g.attr(rankdir='TB')

    # --- Configuration des Styles ---

    # Vert pour le début et la fin (Cercles/Ellipses)
    g.attr('node', style='filled', color='seagreen', fillcolor='honeydew', shape='ellipse')
    g.node('A', 'Début Heuristique améliorée')
    g.node('K', 'Solution finale')

    # Orange pour les questions (Losanges)
    g.attr('node', color='darkorange', fillcolor='papayawhip', shape='diamond')
    g.node('E', 'Date d\'interruption réalisable?')
    g.node('H', 'Plus de centrales?')
    g.node('I', 'cpt < |I_2| ?')

    # Bleu pour les actions (Rectangles)
    g.attr('node', color='steelblue', fillcolor='aliceblue', shape='box')
    g.node('B', 'Calculer scores de priorité Wi\nET\nTrier les centrales par Wi décroissant')
    g.node('C', 'Unité sans créneau réalisable : cpt=0')
    g.node('D', 'Sélectionner la première centrale')
    g.node('F', 'Planifier l\'interruption\nMettre à jour y, x')
    g.node('G', 'Rien planifier ; cpt+1')
    g.node('J', 'Résoudre le PL pour p, s, r')

    # --- Définition des Arêtes ---

    g.edges([
        ('A', 'B'),
        ('B', 'C')
    ])

    # Partie identique à la version précédente → en pointillés
    g.edge('C', 'D',)
    g.edge('D', 'E', style='dashed')

    g.edge('E', 'F', label='Yes', style='dashed')
    g.edge('E', 'G', label='No', style='dashed')

    g.edge('G', 'H', style='dashed')
    g.edge('F', 'H', style='dashed')

    g.edge('H', 'D', label='Yes', style='dashed')

    # Partie spécifique multi-campagnes
    g.edge('H', 'I', label='No')
    g.edge('I', 'C', label='Yes')
    g.edge('I', 'J', label='No')

    g.edge('J', 'K')

    g.render(str(OUTPUT_DIR / 'heuristic_campaign_multiple_flowchart'), view=True)

    
def flowChart_heu_RF():

    g = Digraph(format='png')
    g.attr(rankdir='TB')

    # --- Start / End ---
    g.attr('node', style='filled', color='seagreen', fillcolor='honeydew', shape='ellipse')
    g.node('A', 'Début Heuristique améliorée\nRandom Forest')
    # g.node('N', 'Solution finale')

    # --- Decisions ---
    g.attr('node', color='darkorange', fillcolor='papayawhip', shape='diamond')
    g.node('B', 'Modèle priorité en cache ?')
    g.node('F', 'Modèle dates en cache ?')
    g.node('K', 'Créneau faisable trouvé ?')

    # --- Actions ---
    g.attr('node', color='steelblue', fillcolor='aliceblue', shape='box')
    g.node('C', 'Construction features centrales type 2')
    g.node('D', 'Entraînement RandomForestRegressor')
    g.node('E', 'Prédiction scores W_i et tri centrales')

    g.node('G', 'Construction dataset dates maintenance')
    g.node('H', 'Entraînement RandomForestClassifier')
    g.node('I', 'Prédiction meilleurs t_start candidats')

    g.node('J', 'Test capacité restante / faisabilité')
    g.node('L', '(pareil que heuristique basic...)')
    # g.node('L', 'Fixer x_itk et y_it')
    # g.node('M', 'Résolution PL production + recharge (HiGHS)')

    # --- Edges ---
    g.edge('A', 'B')

    # Priority model
    g.edge('B', 'E', label='Oui')
    g.edge('B', 'C', label='Non')
    g.edge('C', 'D')
    g.edge('D', 'E')

    # Start-date model
    g.edge('E', 'F')
    g.edge('F', 'I', label='Oui')
    g.edge('F', 'G', label='Non')
    g.edge('G', 'H')
    g.edge('H', 'I')

    # Scheduling loop
    g.edge('I', 'J')
    g.edge('J', 'K')
    g.edge('K', 'L', label='Oui')
    g.edge('K', 'I', label='Non')

    # Final LP
    # g.edge('L', 'M')
    # g.edge('M', 'N')

    g.render(str(OUTPUT_DIR / 'heuristic_basic+MILP_flowchart'), view=True)   

import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np

def draw_maintenance_schedule_production(
    prod_data: dict,
    units: list,
    title: str,
    maintenance_blocks: list,
    recharge_blocks: list,
    sols_blocks: list = None,
):
    # --- Configuration ---
    # Production values (normalized to fit within the unit's vertical space)
    # Max height for curve will be ~0.4 units above the baseline
    if not prod_data:
        lengths = {}    
    else:
        lengths = {key: len(value) for key, value in prod_data.items()}
    print("Summary of lengths:", lengths)
    
    t_max = 139
    x_limit = t_max + 10
    weeks_ticks = range(0, 134, 7)

    fig, ax = plt.subplots(figsize=(9, 5))

    # --- Draw Axes and Labels ---
    for y, name in units:
        ax.arrow(0, y, x_limit, 0, head_width=0.12, head_length=2, 
                 fc='black', ec='black', length_includes_head=True)
        ax.text(x_limit + 2, y, "jours", va='center', fontsize=9)
        ax.plot([0, 0], [y - 0.5, y + 0.5], color='black', linewidth=1)
        ax.text(-5, y, name, ha='right', va='center', fontsize=10)
        
        for t in weeks_ticks:
            ax.plot([t, t], [y - 0.08, y + 0.08], color='black', linewidth=0.8)

        if y in prod_data:
            vals = np.array(prod_data[y])
            n = len(vals)
            # x coordinates matching the number of samples in this series
            # Start at integer days (0,1,2,...) so curves align with rectangles/ticks
            x_vals = np.arange(0, n, 1.0)
            max_val = max(vals) if max(vals) > 0 else 1
            # Scaling: 0.4 is the peak height, y is the baseline
            norm_vals = y + (vals / max_val) * 0.4
            ax.plot(x_vals, norm_vals, color='blue', linewidth=1.5, alpha=0.85, zorder=4)
            # Label "prod." like in the reference image
            # ax.text(-2, y + 0.45, "prod.", fontsize=8, ha='right')

    
    # Parse maintenance blocks and separate by type
    gray_blocks = []
    green_blocks = []
    orange_blocks = recharge_blocks 
    
    for block in maintenance_blocks:
        unit_y, start, duration, block_type = block
        if block_type == "gray":
            gray_blocks.append((unit_y, start, duration))
        elif block_type == "green":
            green_blocks.append((unit_y, start, duration))
    
    # Draw gray maintenance windows
    for unit_y, start, duration in gray_blocks:
        ax.add_patch(patches.Rectangle((start, unit_y - 0.25), duration, 0.5, 
                                       color='#e0e0e0', zorder=1))
    
    # Draw green scheduled maintenance blocks
    for unit_y, start, duration in green_blocks:
        ax.add_patch(patches.Rectangle((start, unit_y - 0.25), duration, 0.5, 
                                       facecolor='#99ff99', edgecolor='black', 
                                       linewidth=1, zorder=2))
        # Calculate text position (center of block)
        text_x = start + duration / 2
        text_y = unit_y + 0.3
        ax.text(
            text_x,
            text_y,
            f"Arrêt ({int(duration)}j)",
            ha='center',
            va='bottom',
            fontsize=8,
            zorder=20,
            bbox=dict(facecolor='white', edgecolor='none', alpha=0.75, pad=0.4),
        )

    # Draw recharge inside the green box, with the vertical position reflecting r_it.
    recharge_by_unit = {}
    for block in orange_blocks:
        if len(block) >= 4:
            unit_y, start, value, _ = block
        else:
            unit_y, start, value = block
        recharge_by_unit.setdefault(unit_y, []).append((start, value))

    green_blocks_by_unit = {}
    for unit_y, start, duration in green_blocks:
        green_blocks_by_unit.setdefault(unit_y, []).append((start, duration))

    for unit_y, points in recharge_by_unit.items():
        if unit_y not in green_blocks_by_unit:
            continue

        points.sort(key=lambda item: item[0])
        for green_start, green_duration in green_blocks_by_unit[unit_y]:
            green_end = green_start + green_duration
            interval_points = [
                (start, value)
                for start, value in points
                if green_start <= start <= green_end
            ]

            if not interval_points:
                continue

            values = np.array([value for _, value in interval_points], dtype=float)
            avg_value = float(np.mean(values))
            max_value = float(np.max(values)) if np.max(values) > 0 else 1.0

            # Base slope stays inside the box, and increases with recharge intensity.
            box_bottom = unit_y - 0.18
            box_top = unit_y + 0.18
            slope = 0.08 + 0.22 * (avg_value / max_value)
            # Anchor the starting point at the unit tick (baseline y) instead of
            # the bottom of the green box so the recharge begins at the tick.
            y_start = float(unit_y)

            # Prefer to stop the recharge trace where production resumes for this unit
            # inside the green window. If production starts at t_prod, end there;
            # otherwise end at the green window right edge.
            prod_series = prod_data.get(unit_y, None)
            prod_start = None
            if prod_series is not None:
                series_len = len(prod_series)
                for tt in range(green_start, min(series_len, green_end + 1)):
                    if prod_series[tt] > 0:
                        prod_start = tt
                        break

            x_end = prod_start if prod_start is not None else green_end

            # Add a small, deterministic variation per window so different
            # recharge events don't all end at the exact same height.
            pseudo = ((int(unit_y) * 131 + int(green_start) * 17) % 100) / 100.0
            # Larger variation range for more noticeable differences
            variation = 0.6 + 0.8 * pseudo

            # y_end computed based on the actual x_end distance
            y_end = min(box_top, y_start + slope * (x_end - green_start) * variation)

            # Keep the second segment only: start at the green window and end at its right edge.
            variation = 0.6 + 0.8 * pseudo
            y_end = min(box_top, y_start + slope * (green_end - green_start) * variation)

            ax.plot(
                [green_start, green_end],
                [y_start, y_end],
                color='red',
                linewidth=1.3,
                solid_capstyle='round',
                zorder=10,
            )
            ax.scatter([green_start, green_end], [y_start, y_end], color='red', s=10, zorder=11)

    # --- Plot `sol._sols` curve (per-time stock) for type-2 units, if provided ---
    if sols_blocks:
        sols_events = {}
        max_sols_t = 0
        for blk in sols_blocks:
            if len(blk) >= 4:
                u_y, t, val, _tag = blk
            else:
                u_y, t, val = blk
            try:
                t_i = int(t)
                v_f = float(val)
            except Exception:
                continue
            sols_events.setdefault(u_y, []).append((t_i, v_f))
            if t_i > max_sols_t:
                max_sols_t = t_i

        series_len_sols = t_max + 1
        if prod_data:
            series_len_sols = max(series_len_sols, max((len(v) for v in prod_data.values()), default=series_len_sols))
        if max_sols_t:
            series_len_sols = max(series_len_sols, max_sols_t + 2)

        for unit_y, events in sols_events.items():
            name = next((n for (idx, n) in units if idx == unit_y), "")
            if "(type 2)" not in name:
                continue

            arr = np.zeros(series_len_sols, dtype=float)
            for t_i, v_f in events:
                if 0 <= t_i < series_len_sols:
                    arr[t_i] = v_f

            if arr.max() <= 0:
                continue

            # scale to fit inside unit vertical space
            norm = (arr / float(arr.max())) * 0.35
            x_vals = np.arange(series_len_sols)
            y_vals = unit_y + norm

            mask = arr > 0
            if mask.any():
                ax.plot(x_vals[mask], y_vals[mask], color='orange', linewidth=0.25, linestyle='-', zorder=1.5)
                ax.scatter(x_vals[mask], y_vals[mask], color='orange', s=4, zorder=1.5)

    # --- Legend (positioned at top, under title) ---
    legend_boxes_y = 4.4
    legend_lines_y = 4.02
    ax.add_patch(patches.Rectangle((10, legend_boxes_y - 0.2), 5, 0.3, facecolor='#e0e0e0', edgecolor='black'))
    ax.text(17, legend_boxes_y , "Fenêtres de début $K_i$", va='center', fontsize=10)
    ax.add_patch(patches.Rectangle((70, legend_boxes_y - 0.2), 5, 0.3, facecolor='#99ff99', edgecolor='black'))
    ax.text(77, legend_boxes_y , "Maintenance choisie ($y_{it}=1$)", va='center', fontsize=10)
    ax.plot([10, 15], [legend_lines_y, legend_lines_y], color='blue', linewidth=2)
    ax.text(17, legend_lines_y, "Courbe de production ($p_{it}$)", va='center', fontsize=10)
    ax.plot([70, 75], [legend_lines_y, legend_lines_y], color='red', linewidth=2.5, solid_capstyle='round')
    ax.text(77, legend_lines_y, "Recharge ($r_{it}$)", va='center', fontsize=10)
    ax.plot([10, 15], [legend_lines_y - 0.28, legend_lines_y - 0.28], color='orange', linewidth=0.5)
    ax.text(17, legend_lines_y - 0.28, "Stock ($s_{it}$)", va='center', fontsize=10)

    # --- Formatting ---
    ax.set_xlim(-30, x_limit + 8)
    ax.set_ylim(-0.6, 5.0)
    ax.axis('off')
    plt.title(title, 
              y=0.98, fontsize=13, fontweight='bold')

    plt.savefig(OUTPUT_DIR / f"{title.replace(' ', '_')}.png", bbox_inches='tight', dpi=300)
    plt.show()
    
import re
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


class TERPlots:
    """
    Generate comparison plots from LaTeX result tables.

    INPUTS
    ------
    milp_tex_file : str
        Path to LaTeX file containing MILP table.

    heuristic_tex_file : str
        Path to LaTeX file containing heuristic comparison table.

    The heuristic table must contain columns like:
        Data | S | VAL | Gap | CPU

    The MILP table must contain:
        Data | S | BD | CPU_1

    Gap formula assumed:
        Gap(%) = (VAL - BD)/BD * 100

    OUTPUT
    ------
    Saves:
        - gap_comparison.png
        - cpu_comparison.png
        - quality_vs_runtime.png
    """

    def __init__(
        self,
        milp_tex_file: str | None = None,
        heuristic_tex_file: str = "",
        relax_lag_tex_file: str = "",
        relax_lag_file: str = "",
    ):
        self.milp_tex_file = milp_tex_file
        self.heuristic_tex_file = heuristic_tex_file
        self.relax_lag_file = relax_lag_tex_file or relax_lag_file

        self.milp_df = pd.DataFrame(columns=["Instance", "BD", "MILP_CPU"])
        self.heuristic_df = None
        self.relax_lag_df = None

    # =========================================================
    # ---------------- LATEX TABLE PARSING --------------------
    # =========================================================

    def _clean_value(self, x):
        x = str(x).strip()

        x = x.replace("\\", "")
        x = x.replace("%", "")
        x = x.replace("s", "")
        x = x.replace("--", "")
        x = x.replace("Irréal.", "")
        x = x.replace("inf", "")
        x = x.replace(" ", "")

        try:
            return float(x)
        except:
            return np.nan

    def _extract_rows(self, text):
        rows = []

        for line in text.splitlines():

            if "&" not in line:
                continue

            if "\\hline" in line:
                continue

            if "textbf" in line:
                continue

            line = line.replace("\\\\", "")
            parts = [p.strip() for p in line.split("&")]

            rows.append(parts)

        return rows

    # =========================================================
    # ---------------------- MILP -----------------------------
    # =========================================================

    def parse_milp_table(self):

        if not self.milp_tex_file:
            self.milp_df = pd.DataFrame(columns=["Instance", "BD", "MILP_CPU"])
            return

        with open(self.milp_tex_file, "r", encoding="utf-8") as f:
            text = f.read()

        rows = self._extract_rows(text)

        data = []

        for row in rows:

            if len(row) < 8:
                continue

            instance = row[0]
            scenario = row[1]

            bd = self._clean_value(row[3])
            cpu = self._clean_value(row[7])

            data.append({
                "Instance": f"{instance}-S{scenario}",
                "BD": bd,
                "MILP_CPU": cpu
            })

        self.milp_df = pd.DataFrame(data)

    # =========================================================
    # ------------------- HEURISTICS --------------------------
    # =========================================================

    def parse_heuristic_table(self):

        with open(self.heuristic_tex_file, "r", encoding="utf-8") as f:
            text = f.read()

        table_blocks = re.findall(
            r"\\begin\{table\}.*?\\end\{table\}",
            text,
            flags=re.DOTALL
        )

        data = []

        for block in table_blocks:
            rows = self._extract_rows(block)

            heuristic_names = re.findall(
                r"\\textbf\{([^}]*)\}",
                block
            )

            heuristic_names = [
                h for h in heuristic_names
                if "Instances" not in h
                and "Data" not in h
                and "S" not in h
                and "VAL" not in h
                and "Gap" not in h
                and "CPU" not in h
            ]

            if len(heuristic_names) < 2:
                continue

            h1_name, h2_name = heuristic_names[:2]

            heuristic_pairs = [
                (h1_name, 3, 4),
                (h2_name, 6, 7),
            ]

            for row in rows:

                if len(row) < 8:
                    continue

                instance = row[0]
                scenario = row[1]

                instance_name = f"{instance}-S{scenario}"

                for heuristic_name, gap_idx, cpu_idx in heuristic_pairs:
                    if "RF" in heuristic_name.upper():
                        continue

                    data.append({
                        "Instance": instance_name,
                        "Heuristique": heuristic_name,
                        "Gap": self._clean_value(row[gap_idx]),
                        "CPU": self._clean_value(row[cpu_idx])
                    })

        self.heuristic_df = pd.DataFrame(data)
        heuristics = list(self.heuristic_df["Heuristique"].unique()) if not self.heuristic_df.empty else []
        if Path(self.heuristic_tex_file).name == "tableau_LPrelax_Lagrelax.tex" and len(heuristics) >= 2:
            self.colors = {
                heuristics[0]: "green",
                heuristics[1]: "red",
            }
        else:
            # Assign consistent colors for heuristics using matplotlib default cycle
            prop_colors = plt.rcParams.get('axes.prop_cycle').by_key().get('color', [])
            self.colors = {h: prop_colors[i % len(prop_colors)] for i, h in enumerate(heuristics)}

    def parse_relax_lag_results(self):

        if not self.relax_lag_file:
            self.relax_lag_df = pd.DataFrame(columns=["Instance", "Gap", "CPU"])
            return

        relax_path = Path(self.relax_lag_file)
        if not relax_path.exists() or relax_path.is_dir():
            self.relax_lag_df = pd.DataFrame(columns=["Instance", "Gap", "CPU"])
            return

        pattern = re.compile(
            r"^(?P<instance>\S+)\s+s\s*=\s*(?P<scenario>\d+)\s+bd\s*=\s*(?P<bd>[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?)\s+gap\s*=\s*(?P<gap>[+-]?(?:\d+(?:\.\d*)?|\.\d+))%\s+secondes\s*=\s*(?P<cpu>[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?)",
            flags=re.IGNORECASE,
        )

        data = []
        with open(relax_path, "r", encoding="utf-8") as f:
            for raw_line in f:
                line = raw_line.strip()
                if not line:
                    continue

                match = pattern.match(line)
                if not match:
                    continue

                instance = match.group("instance")
                scenario = match.group("scenario")

                data.append({
                    "Instance": f"{instance}-S{scenario}",
                    "Gap": self._clean_value(match.group("gap")),
                    "CPU": self._clean_value(match.group("cpu")),
                })

        self.relax_lag_df = pd.DataFrame(data)

    # =========================================================
    # ------------------- FIGURE 1 ----------------------------
    # =========================================================

    def plot_gap_comparison(self):
        # Compute mean gap per heuristic (average across instances)
        if self.heuristic_df is None or self.heuristic_df.empty:
            print("No heuristic data to plot GAPs")
            return

        # Mean gap per heuristic
        mean_gap = self.heuristic_df.groupby("Heuristique")["Gap"].mean()

        # If any mean is non-positive, fall back to mean absolute gap
        use_abs = False
        if (mean_gap <= 0).any():
            mean_gap = self.heuristic_df.groupby("Heuristique")["Gap"].apply(lambda x: np.nanmean(np.abs(x)))
            ylabel = "Moyen |Gap| (%) [log scale]"
            use_abs = True
        else:
            ylabel = "Gap Moyen (%) [log scale]"

        # use consistent heuristic colors
        colors = [self.colors.get(h, None) for h in mean_gap.index]
        ax = mean_gap.plot(kind="bar", figsize=(12, 6), color=colors)

        # Log scale (use absolute means when necessary to ensure positivity)
        ax.set_yscale("log")
        ax.set_ylabel(ylabel, fontsize=PLOT_AXIS_LABEL_SIZE)
        ax.set_xlabel("Heuristique", fontsize=PLOT_AXIS_LABEL_SIZE)
        ax.set_title("Moyenne des GAPs par heuristique", fontsize=PLOT_TITLE_SIZE)
        ax.grid(True)

        plt.xticks(rotation=45)
        plt.tight_layout()

        plt.savefig(
            OUTPUT_DIR / "gap_comparison.png",
            dpi=300,
            bbox_inches="tight"
        )

        plt.close()

    # =========================================================
    # ------------------- FIGURE 2 ----------------------------
    # =========================================================

    def plot_cpu_comparison(self):

        if self.heuristic_df is None or self.heuristic_df.empty:
            print("No heuristic data to plot CPU comparisons")
            return

        cpu_df = self.heuristic_df.pivot_table(
            index="Instance",
            columns="Heuristique",
            values="CPU"
            , aggfunc="first"
        )

        if self.milp_df is not None and not self.milp_df.empty:
            milp_cpu = self.milp_df.set_index("Instance")["MILP_CPU"]
            cpu_df["MILP"] = milp_cpu

        # set colors for each column (heuristics + optional MILP)
        col_colors = []
        for col in cpu_df.columns:
            if col == "MILP":
                col_colors.append('gray')
            else:
                col_colors.append(self.colors.get(col, None))
        ax = cpu_df.plot(kind="bar", figsize=(14,6), color=col_colors)

        ax.set_yscale("log")
        ax.set_ylabel("CPU Temps (s) [log scale]", fontsize=PLOT_AXIS_LABEL_SIZE)
        ax.set_xlabel("Instance", fontsize=PLOT_AXIS_LABEL_SIZE)
        ax.set_title("Comparaison des temps CPU", fontsize=PLOT_TITLE_SIZE)
        ax.grid(True)

        plt.xticks(rotation=45)
        plt.tight_layout()

        plt.savefig(
            OUTPUT_DIR / "cpu_comparison.png",
            dpi=300,
            bbox_inches="tight"
        )

        plt.close()

    # =========================================================
    # ------------------- FIGURE 3 ----------------------------
    # =========================================================

    def plot_quality_vs_runtime(self):

        plt.figure(figsize=(10, 7))

        heuristics = self.heuristic_df["Heuristique"].unique()

        legend_seen = set()

        for h in heuristics:

            subset = self.heuristic_df[
                self.heuristic_df["Heuristique"] == h
            ]

            subset = subset[subset["CPU"] > 0]
            if subset.empty:
                continue

            plt.scatter(
                subset["CPU"],
                subset["Gap"],
                s=80,
                label=h if h not in legend_seen else None,
                color=self.colors.get(h, None),
                alpha=0.65,
                edgecolors='none',
                zorder=10
            )
            legend_seen.add(h)

        if self.relax_lag_df is not None and not self.relax_lag_df.empty:
            lag_plot = self.relax_lag_df.dropna(subset=["CPU", "Gap"])
            lag_plot = lag_plot[lag_plot["CPU"] > 0]
            if not lag_plot.empty:
                plt.scatter(
                    lag_plot["CPU"],
                    lag_plot["Gap"],
                    s=90,
                    marker='o',
                    color='red',
                    label='Relax. Lag.',
                    alpha=0.55,
                    edgecolors='none',
                    zorder=12,
                )

        if self.milp_df is not None and not self.milp_df.empty:
            milp_plot = self.milp_df.dropna(subset=["MILP_CPU"])
            milp_plot = milp_plot[milp_plot["MILP_CPU"] > 0]
            if not milp_plot.empty:
                plt.scatter(
                    milp_plot["MILP_CPU"],
                    np.zeros(len(milp_plot)),
                    s=120,
                    marker='X',
                    color='black',
                    label='MILP',
                    alpha=0.85,
                    zorder=1,
                )

        plt.xscale("log")
        plt.xlabel("CPU Time (s)", fontsize=PLOT_AXIS_LABEL_SIZE)
        plt.ylabel("Gap (%)", fontsize=PLOT_AXIS_LABEL_SIZE)
        plt.title("Qualité vs Temps de calcul", fontsize=PLOT_TITLE_SIZE)

        plt.grid(True)
        plt.legend(fontsize=PLOT_LEGEND_SIZE, title_fontsize=PLOT_LEGEND_SIZE)

        plt.tight_layout()

        plt.savefig(
            OUTPUT_DIR / "quality_vs_runtime.png",
            dpi=300,
            bbox_inches="tight"
        )

        plt.close()

    # =========================================================
    # -------------------- MAIN PIPELINE ----------------------
    # =========================================================

    def generate_all_plots(self):

        if self.milp_tex_file:
            self.parse_milp_table()
        self.parse_heuristic_table()
        self.parse_relax_lag_results()

        self.plot_gap_comparison()
        self.plot_cpu_comparison()
        self.plot_quality_vs_runtime()

        print("Plots generated successfully.")

    

def main():
    # flowChart_heu_basic()
    # flowChart_heu_campaign_multiple()
    # flowChart_heu_RF()
    # draw_maintenance_schedule_production()

    base_dir = Path(__file__).resolve().parent
    output_dir = base_dir.parent / "output"
    plots = TERPlots(
        milp_tex_file=str(output_dir / "tableau_milp_resultats.tex"),
        heuristic_tex_file=str(output_dir / "tableaux_heur_resultats.tex")
    )
    plots.generate_all_plots()    

if __name__ == "__main__":
    main()

    

def extract_visualization_data_from_solution(solution, data):
    # Get number of units and timesteps
    n_type1 = data.nbpower1()
    n_type2 = data.nbpower2()
    n_timesteps = data.timestep()

    def _label_type1_unit(unit_index: int) -> str:
        if unit_index == 0:
            return "Charbon (type 1)"
        if unit_index == 1:
            return "Gaz (type 1)"
        return f"Type 1 Unit {unit_index}"

    def _label_type2_unit(power2_unit) -> str:
        unit_name = power2_unit.name()
        if unit_name.startswith("powerplant_2_"):
            suffix = unit_name[len("powerplant_2_"):]
            return f"Nucléaire {suffix} (type 2)"
        return f"{unit_name} (type 2)"
    
    # Extract production data
    prod_data = {}
    
    # Type 1 units production (keys: (i, t))
    for i in range(n_type1):
        prod_values = []
        for t in range(n_timesteps):
            prod_values.append(solution._solP1.get((i, t), 0.0))
        if any(v > 0 for v in prod_values):  # Only include if has non-zero production
            prod_data[i] = prod_values
    
    # Type 2 units production (keys: (i, t))
    for i in range(n_type2):
        prod_values = []
        for t in range(n_timesteps):
            prod_values.append(solution._solP2.get((i, t), 0.0))
        if any(v > 0 for v in prod_values):  # Only include if has non-zero production
            prod_data[n_type1 + i] = prod_values
    
    # Build K_i and K_i_simple from campaign windows in data
    horizon_last_t = n_timesteps - 1
    campaign_ids_by_unit = [
        range(len(data.accessPower2(i).Campaigns()))
        for i in range(n_type2)
    ]

    K_i = []
    for i in range(n_type2):
        campaigns_i = []
        for k in campaign_ids_by_unit[i]:
            start = max(0, data.accessCampaign(i, k).earlieststop())
            end = min(horizon_last_t, data.accessCampaign(i, k).lateststop())
            k_range = list(range(start, end + 1))
            if k_range != [0]:
                campaigns_i.append(k_range)
        K_i.append(campaigns_i)

    K_i_simple = {}
    for i in range(n_type2):
        K_i_simple[i] = [t for campagne in K_i[i] for t in campagne]

    # Build gray maintenance windows from K_i
    maintenance_blocks_gray = []
    for i in range(n_type2):
        unit_y = n_type1 + i
        for k_range in K_i[i]:
            if not k_range:
                continue
            start = k_range[0]
            duration = len(k_range)
            maintenance_blocks_gray.append((unit_y, start, duration, "gray"))

    # Extract green maintenance blocks.
    # Prefer solx (campaign start decisions + known outage duration),
    # then fall back to grouped soly values if solx is unavailable.
    maintenance_blocks_green = []
    built_from_solx = False

    if hasattr(solution, "_solx") and solution._solx:
        try:
            for (i, k, t_start), value in solution._solx.items():
                if i < 0 or i >= n_type2:
                    continue
                if float(value) < 0.5:
                    continue

                start = int(t_start)
                duration = int(round(float(data.accessCampaign(i, k).durationoutage())))
                if duration <= 0:
                    continue

                start = max(0, start)
                end = min(horizon_last_t, start + duration - 1)
                if end < start:
                    continue

                unit_y = n_type1 + i
                maintenance_blocks_green.append((unit_y, start, end - start + 1, "green"))

            if maintenance_blocks_green:
                built_from_solx = True
        except Exception:
            maintenance_blocks_green = []
            built_from_solx = False

    if not built_from_solx:
        # Fallback: group consecutive maintenance times from soly.
        for i in range(n_type2):
            maintenance_times = []
            for t in range(n_timesteps):
                # Robust threshold for noisy values from relaxed models.
                if float(solution._soly.get((i, t), 0.0)) >= 0.5:
                    maintenance_times.append(t)

            if maintenance_times:
                blocks = []
                start = maintenance_times[0]
                end = start

                for t in maintenance_times[1:]:
                    if t == end + 1:
                        end = t
                    else:
                        blocks.append((start, end - start + 1))
                        start = t
                        end = t
                blocks.append((start, end - start + 1))

                unit_y = n_type1 + i
                for block_start, block_duration in blocks:
                    maintenance_blocks_green.append((unit_y, block_start, block_duration, "green"))

    maintenance_blocks_green.sort(key=lambda b: (b[0], b[1]))

    # Extract recharge markers from solr
    recharge_blocks = []
    for (i, t), value in solution._solr.items():
        if value and value > 0:
            unit_y = n_type1 + i
            recharge_blocks.append((unit_y, t, float(value), "orange"))

    # Extract sols markers from sol._sols if available
    sols_blocks = []
    if hasattr(solution, "_sols") and solution._sols is not None:
        try:
            for (i, t), value in solution._sols.items():
                if value is not None:
                    unit_y = n_type1 + i
                    sols_blocks.append((unit_y, t, float(value), "sols"))
        except Exception:
            # best-effort: ignore if structure unexpected
            pass

    # Final block list requested: gray windows first, then scheduled green blocks
    maintenance_blocks = maintenance_blocks_gray + maintenance_blocks_green
    # maintenance_blocks =  maintenance_blocks_gray
    
    # Create units list for visualization
    units = []
    for i in range(n_type1):
        if i in prod_data:
            units.append((i, _label_type1_unit(i)))
    for i in range(n_type2):
        unit_y = n_type1 + i
        power2_unit = data.accessPower2(i)
        units.append((unit_y, _label_type2_unit(power2_unit)))
    
    return prod_data, maintenance_blocks, units, recharge_blocks, sols_blocks


def draw_cumulative_production_stack(prod_data: dict, data, scenario_idx: int, units: list, title: str):
    if not prod_data:
        print("No production data to plot")
        return

    # Order units according to provided `units` list when available, otherwise sort keys
    ordered_keys = [u[0] for u in units if u[0] in prod_data]
    if not ordered_keys:
        ordered_keys = sorted(prod_data.keys())

    # length of time series (max across units)
    max_len = max(len(v) for v in prod_data.values())
    t = np.arange(0, max_len)

    # build stacked arrays, padding with zeros where needed
    stack_cols = []
    labels = []
    for k in ordered_keys:
        vals = np.array(prod_data.get(k, [0.0] * max_len), dtype=float)
        if len(vals) < max_len:
            vals = np.pad(vals, (0, max_len - len(vals)), constant_values=0.0)
        stack_cols.append(vals)
        name = next((n for (idx, n) in units if idx == k), f"Unit {k}")
        labels.append(name)
    # keep a parallel list of unit indices for robust color mapping
    ordered_indices = ordered_keys

    # demand series from data
    try:
        demand = data.accessScenario(scenario_idx).demands()
        demand = np.array(demand, dtype=float)
    except Exception:
        demand = None

    # If demand is longer than production series, extend production arrays
    if demand is not None:
        if len(demand) > max_len:
            new_len = len(demand)
            for i in range(len(stack_cols)):
                arr = stack_cols[i]
                if len(arr) < new_len:
                    stack_cols[i] = np.pad(arr, (0, new_len - len(arr)), constant_values=0.0)
            max_len = new_len
        else:
            # pad demand to match production length
            if len(demand) < max_len:
                demand = np.pad(demand, (0, max_len - len(demand)), constant_values=np.nan)

    t = np.arange(0, max_len)

    # Use fixed color mapping to match example graph
    # Mapping by unit name keywords -> color
    name_to_color = {
        'Nucléaire 2': '#ffd700',  # yellow
        'Nucléaire 1': '#2e8b57',  # green
        'Charbon': '#89C2F0',      # light blue
        'Gaz': '#e6cfe6',          # light purple/pink
    }

    colors = []
    # assign colors using unit index as authoritative value (robust)
    for idx, lbl in enumerate(labels):
        unit_idx = ordered_indices[idx]
        c = None
        # special-case: absolute unit index 3 -> yellow
        if unit_idx == 3:
            c = '#ffd700'

        if c is None:
            # pick a color by exact or partial match on the label
            for key, col in name_to_color.items():
                if key in lbl:
                    c = col
                    break

        if c is None:
            # fallback to default cycle
            prop_colors = plt.rcParams.get('axes.prop_cycle').by_key().get('color', [])
            c = prop_colors[len(colors) % max(1, len(prop_colors))]

        colors.append(c)

    plt.figure(figsize=(12, 5))
    plt.stackplot(t, *stack_cols, labels=labels, colors=colors, alpha=0.9)

    # Plot demand line (red) without adding legend entry in main plot
    if demand is not None:
        plt.plot(t, demand, color='#d62728', linewidth=4.0, zorder=10)
        plt.scatter(t, demand, color='#d62728', s=30, marker='^', zorder=11)

    plt.xlabel('Pas du temps (jours)')
    plt.ylabel('Production')
    plt.title(title)
    # Legend is intentionally omitted from the main plot. Return labels/colors so caller
    # can create and save a separate legend graphic.
    plt.grid(alpha=0.3)

    safe_name = title.replace(' ', '_')
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / f"{safe_name}.png", dpi=300, bbox_inches='tight')
    plt.show()

    return labels, colors


def save_stack_legend(labels: list, colors: list, filename: str, include_demand: bool = True):
    fig, ax = plt.subplots(figsize=(6, 1.2))
    ax.axis('off')

    # Create legend handles
    handles = []
    from matplotlib.patches import Patch
    from matplotlib.lines import Line2D

    if include_demand:
        handles.append(Line2D([0], [0], marker='^', color='w', label='Demande',
                              markerfacecolor='#d62728', markersize=10))

    # Add colored boxes for each production label (order should match stack)
    for lbl, col in zip(labels, colors):
        handles.append(Patch(facecolor=col, edgecolor='black', label=lbl))

    legend = ax.legend(handles=handles, ncol=len(handles), frameon=False, loc='center',
                       fontsize=10)

    outpath = OUTPUT_DIR / filename
    fig.savefig(outpath, bbox_inches='tight', dpi=300)
    plt.close(fig)


def main():
    units = [
        # (6, "Panneau solaire ($i=1$)"),
        # (5, "Éolienne ($i=2$)"),
        (4, "Gaz ($i=3$)"),
        (3, "Charbon ($i=4$)"),
        (2, "Nucléaire 1 ($i=5$)"),
        (1, "Nucléaire 2 ($i=6$)")
    ]     
    # sol realisable avec prod de 20w
    # prod_data = {
    #     4: [70.0, 90.0, 100.0, 100.0, 100.0, 60.0, 100.0, 100.0, 100.0, 0.0, 100.0, 100.0, 100.0, 100.0, 70.0, 90.0, 100.0, 0.0, 100.0, 60.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 70.0, 90.0, 100.0, 100.0, 100.0, 60.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 70.0, 90.0, 100.0, 100.0, 100.0, 60.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 70.0, 90.0, 100.0, 0.0, 100.0, 0.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 0.0, 90.0, 100.0, 100.0, 100.0, 0.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 0.0, 90.0, 100.0, 100.0, 100.0, 0.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 70.0, 90.0, 100.0, 100.0, 100.0, 60.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 70.0, 90.0, 100.0, 100.0, 100.0, 60.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 0.0, 70.0, 90.0, 100.0, 100.0, 100.0, 60.0, 0.0, 100.0, 35.0, 10.0, 100.0, 30.0, 100.0],
    #     3: [80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0],
    #     2: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 10.0, 0.0, 0.0, 47.0, 10.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 50.0, 30.0, 10.0, 0.0, 40.0, 10.0, 20.0, 50.0, 60.0, 70.0, 50.0, 10.0, 0.0, 0.0, 50.0, 30.0, 10.0, 0.0, 40.0, 10.0, 20.0, 50.0, 60.0, 70.0, 50.0, 10.0, 0.0, 0.0, 50.0, 130.0, 10.0, 60.0, 0.0, 10.0, 20.0, 50.0, 60.0, 70.0, 50.0, 10.0, 0.0, 0.0, 0.0, 0.0, 10.0, 60.0, 40.0, 0.0, 20.0, 0.0, 60.0, 37.92, 50.0, 10.0, 70.0, 0.0, 50.0, 30.0, 10.0, 60.0, 40.0, 10.0, 20.0, 50.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 60.0, 70.0, 50.0, 10.0, 0.0, 0.0, 50.0, 30.0, 10.0, 0.0, 40.0, 10.0, 20.0, 50.0, 60.0, 70.0, 50.0, 110.0, 0.0, 0.0, 50.0, 30.0, 10.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    #     1: [0.0, 0.0, 50.0, 30.0, 10.0, 0.0, 40.0, 10.0, 20.0, 140.0, 60.0, 70.0, 2.916, 0.0, 0.0, 0.0, 50.0, 130.0, 10.0, 0.0, 40.0, 10.0, 20.0, 50.0, 60.0, 70.0, 50.0, 10.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 40.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 70.0, 0.0, 50.0, 30.0, 0.0, 0.0, 0.0, 10.0, 0.0, 50.0, 0.0, 32.08, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 60.0, 70.0, 50.0, 10.0, 0.0, 0.0, 50.0, 30.0, 10.0, 0.0, 40.0, 10.0, 20.0, 50.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 140.0, 10.0, 85.0, 140.0, 60.0, 140.0, 50.0],
    # }
    # sol real isable avec prod de 10w
    # prod_data = {
    #     4: [70, 90, 100, 100, 100, 60, 100, 100, 100, 0, 100, 100, 100, 100, 70, 90, 100, 0, 100, 60, 100, 100, 100, 100, 100, 100, 100, 100, 70, 90, 100, 100, 100, 60, 100, 100, 100, 100, 100, 100, 100, 100, 70, 90, 100, 100, 100, 60, 100, 100, 100],       # Gaz
    #     3: [80]*51,     # Charbon
    #     2: [0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 47.0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50, 30, 10, 0, 40, 10, 20, 50, 60, 70, 50, 10, 0, 0, 50, 30, 10, 0, 40, 10, 20],        # Nucl 1
    #     1: [0, 0, 50, 30, 10, 0, 40, 10, 20, 140, 60, 70, 2.916, 0, 0, 0, 50, 130, 10, 0, 40, 10, 20, 50, 60, 70, 50, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],       # Nucl 2
    # } 
    # # sol realisable dans le rapport avec toy
    # maintenance_blocks_green = [
    #     (2, 14, 14, "green"),    # Unit 5: green maintenance start=14, duration=14
    #     (2, 94, 13, "green"),    # Unit 5: green maintenance start=94, duration=13
    #     (1, 42, 14, "green"),    # Unit 6: green maintenance start=42, duration=14
    #     (1, 112, 14, "green"),   # Unit 6: green maintenance start=112, duration=14
    # ]    
    # maintenance_blocks_gray = [
    #     (2, 7, 21, "gray"),      # Unit 5: gray window start=7, duration=21
    #     (2, 98, 35, "gray"),     # Unit 5: gray window start=98, duration=35
    #     (1, 14, 42, "gray"),     # Unit 6: gray window start=14, duration=42
    #     (1, 105, 28, "gray"),    # Unit 6: gray window start=105, duration=28
    # ]  

    # maintenance_blocks = maintenance_blocks_gray + maintenance_blocks  


    # draw_maintenance_schedule_production(prod_data, units, "Exemple de solution réalisable avec production de 20W", maintenance_blocks_green)


    # flowChart_heu_basic()
    # flowChart_heu_campaign_multiple()
    # flowChart_heu_improved_extension()
    # flowChart_heu_RF()

    base_dir = Path(__file__).resolve().parent
    output_dir = base_dir.parent / "output"
    plots = TERPlots(
        # milp_tex_file=str(output_dir / "tableau_milp_resultats.tex"),
        heuristic_tex_file=str(output_dir / "tableau_LPrelax_Lagrelax.tex"),
        # heuristic_tex_file=str(output_dir / "tableaux_heur_resultats.tex"),
        # relax_lag_tex_file=str(output_dir / "gap_relaxLag.txt")
    )
    plots.generate_all_plots()    

if __name__ == "__main__":
    main()



   

